RPH/RPH/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('punchline.urls')),
]
if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RPH/punchline/urls.py
from django.urls import path
from . import views
from .views import (
                    PostListView,
                    PunchlineDetailView,
                    add_comment_to_punchline,
                    search,
                    )



urlpatterns=[

path('',PostListView.as_view(),name='post-home'),
path('search',views.search, name='search'),
path('punchline/<int:pk>/detail/', PunchlineDetailView.as_view(), name='punchline_detail'),

path('punchline/<int:pk>/comment/', views.add_comment_to_punchline, name='add_comment_to_punchline'),

]

RPH/punchline/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Artiste(models.Model):
    nom = models.CharField(max_length=100)
    image = models.ImageField(default='default.jpg',upload_to='artiste_punchline_image',null=True)

    def __str__(self):
        return self.nom

class Album(models.Model):
    nom = models.CharField(max_length=100)

    def __str__(self):
        return self.nom
class Punchline(models.Model):
    punchline_contenu = models.CharField(max_length=250)
    poster_par = models.ForeignKey(User,on_delete = models.CASCADE)
    date_poste = models.DateTimeField(default=timezone.now)
    rappeur = models.ForeignKey(Artiste,on_delete=models.CASCADE)
    rappeur_album = models.ForeignKey(Album,on_delete=models.CASCADE)
    def __str__(self):
        return self.punchline_contenu


class Comment(models.Model):
    punchline = models.ForeignKey(Punchline,on_delete=models.CASCADE,related_name='comments',null=True)
    #,null=True,blank=True
    auteur =models.CharField(max_length=200)
    text = models.TextField()
    date_comment = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

RPH/punchline/forms.py
from django import forms
from .models import Punchline,Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('auteur','text',)

RPH/punchline/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Punchline,Comment
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .forms import CommentForm
# Create your views here.

def search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None
    if q:
        context ={'query':q}
        template = 'punchline/result.html'

    else:
        template = 'punchline/punchline_list.html'
        context ={}
    return render(request,template,context)

    pass

def add_comment_to_punchline(request, pk):
    punchline = get_object_or_404(Punchline, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.puncline = punchline
            comment.save()
            return redirect('punchline_detail', pk=punchline.pk)
    else:
        form = CommentForm()
    return render(request, 'punchline/add_comment_to_post.html', {'form': form})

class PostListView(ListView):
    model = Punchline
    template_name = 'punchline/punchline_list.html'
    context_object_name = 'punchlines'
    ordering = ['-date_poste']
    paginate_by = 10

class PunchlineDetailView(DetailView):
    model = Punchline

RPH/punchline/templates/punchline/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
      {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

RPH/punchline/templates/punchline/punchline_detail.html
{% extends 'base.html' %}

{% block content %}
<hr>
<<h1>love</h1>
		<article class="media content-section">
			<div class="media-body">
				<div class="article-metadata">
					<small class="text-muted">poster par  {{ punchline.poster_par }} </small>
					<small class="text-muted"> le {{ punchline.date_poste|date:"F d ,Y"}} </small>
				</div>
				<img class="rounded-circle article-img" src="{{ punchline.rappeur }}" alt="">
				<a class="mr-2" href="#"> {{ object.rappeur }}</a>
				<h5><a href="{% url 'punchline_detail' pk=punchline.pk %}">{{ object.punchline_contenu|linebreaksbr }}</a></h5>
            <a href="{% url 'punchline_detail' pk=punchline.pk %}">Comments: {{ object.comments.count }}</a>
					<strong><p class="article-content">  </p>	</strong>

          {% for comment in punchline.comments.all %}
            <div class="comment">
              <strong>{{ comment.auteur }}</strong>
                <div class="date">{{ comment.date_comment }}</div>
                <p>{{ comment.text|linebreaks }}</p>
                <hr>
            </div>
          {% empty %}
            <p>No comments here yet :(</p>
          {% endfor %}

			</div>


			</article>
{% endblock content %}

RPH/punchline/templates/punchline/punchline_list.html
{% extends 'base.html'%}


{% block content %}
{% for punchline in punchlines %}
<br>
<br>
<br>
<br>
		<article class="media content-section">
			<div class="media-body">
				<div class="article-metadata">
					<small class="text-muted">poster par  {{ punchline.poster_par }} </small>
					<small class="text-muted">ID: {{ punchline.id }} </small>
					<small class="text-muted"> le {{ punchline.date_poste|date:"F d ,Y"}} </small>
				</div>
				<img class="rounded-circle article-img" src="{{ rappeur.album_set.all }}" alt="">
				<a class="mr-2" href="#"> {{ punchline.rappeur }}</a>
				<h5>«{{ punchline.punchline_contenu }}»</h5>
				<hr>
            <a href="{% url 'punchline_detail' pk=punchline.pk %}">Comments: {{ punchline.comments.count }}</a>
					<strong><p class="article-content">  </p>	</strong>


					{% for comment in punchline.comments.all %}
						<div class="comment">
							<strong>{{ comment.auteur }}</strong>
								<div class="date">{{ comment.date_comment }}</div>
								<p>{{ comment.text|linebreaks }}</p>
								<hr>
						</div>
					{% empty %}
						<p>No comments here yet :(</p>
					{% endfor %}
			</div>

					
			</article>
{% endfor %}

{% endblock content %}

RPH/templates/base.html
{% load static  %}

<!DOCTYPE html>
<html>
<head>
	    <meta charset="utf-8">
<meta mane="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %} ">
        <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap-theme.min.css' %}">
			<title>{% block head_title %} {% endblock head_title %} Blog</title>

</head>
<body>
<div class="container">


	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4"  href="/">Django Blog</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse">
					<span class="navbar=data-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link " href="/">Home</a>
						<a class="nav-item nav-link" href="/">About</a>

											<!-- search form -->
						<form class="form-inline my-2 my-lg-0" action="url 'search'">

								<input class="form-control mr sm-2" type="search" name="q" placeholder="Search by title" aria-label="Search">
								<button class="btn btn-outline-info my-
								 my-sm-0" type="submit" >Search</button>

					 </form>
					</div>

					<!-- Navrbar Right Side -->

				</div>
			</div>
		</nav>
	</header>
</div>

	<div role="main" class="container">

		<div class="row">

			<div class="col-md-8">

													{% block content %} {% endblock content %}

																		</div>
			<div class="col-md-4">
				<div class="content-section">
					<h3>Our sidebar</h3>
					<p class="text-muted">
						<h3>Top 10 puncline par vote</h3>
							<ul class="list-group">
								<li class="list-group-item list-group-item-light">Lastest Posts</li>
								<li class="list-group-item list-group-item-light">Announcement</li>
								<li class="list-group-item list-group-item-light">Calendars</li>
								<li class="list-group-item list-group-item-light">etc..</li>
							</ul>
					</p>
				</div>
			</div>
		</div>

</div>


</body>
</script  href="{% static 'css/bootstrap/js/bootstrap.min.js' %}">

</html>